# Generated by Django 4.2.4 on 2023-09-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_requesttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesttime',
            old_name='user',
            new_name='token',
        ),
        migrations.AlterUniqueTogether(
            name='requesttime',
            unique_together={('token', 'month', 'year')},
        ),
    ]
